[road]
  [road.move]
  _type = "axis"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "left_x"
  keyboard = "arrow_left,arrow_right"

  [road.accelerate]
  _type = "button"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_x"
  keyboard = "z"

  [road.turbo]
  _type = "button"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_y"
  keyboard = "x"

  [road.select]
  _type = "trigger"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_x"
  keyboard = "z"

  [road.quit]
  _type = "button"
  _device_order = ["keyboard"]
  keyboard = "escape"
