[player]
  [player.move]
  _type = "axis"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "left_x"
  keyboard = "arrow_left,arrow_right"

  [player.accelerate]
  _type = "button"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_x"
  keyboard = "z"

  [player.decelerate]
  _type = "button"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "dpad_down"
  keyboard = "arrow_down"

  [player.turbo]
  _type = "button"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_y"
  keyboard = "x"

  [player.slip_debug]
  _type = "trigger"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_z"
  keyboard = "c"


[game]
  [game.move]
  _type = "axis"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "left_x"
  keyboard = "arrow_left,arrow_right"

  [game.select]
  _type = "trigger"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_x"
  keyboard = "enter"

  [game.backspace]
  _type = "trigger"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_y"
  keyboard = "backspace"

  [game.quit]
  _type = "trigger"
  _device_order = ["keyboard"]
  keyboard = "escape"


