[player]
  [player.move]
  _type = "axis"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "left_x"
  keyboard = "arrow_left,arrow_right"

  [player.accelerate]
  _type = "button"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_x"
  keyboard = "arrow_up"

  [player.decelerate]
  _type = "button"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_y"
  keyboard = "arrow_down"

  [player.select]
  _type = "trigger"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_x"
  keyboard = "enter"

  [player.backspace]
  _type = "trigger"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_y"
  keyboard = "backspace"


[game]
  [game.move]
  _type = "axis"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "left_x"
  keyboard = "arrow_left,arrow_right"


  [game.quit]
  _type = "trigger"
  _device_order = ["keyboard"]
  keyboard = "escape"


